env:
  node: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  curly: error
  default-case: error
  eqeqeq:
    - error
    - always
  no-console:
    - warn
    - allow:
        - warn
        - error
  no-implicit-coercion: error
  no-redeclare: error
  no-shadow: error
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-var: error
  prefer-const: error
  consistent-return: error
  complexity:
    - warn
    - max: 10
  max-lines-per-function:
    - warn
    - max: 60
      skipBlankLines: true
      skipComments: true
  max-depth:
    - warn
    - 3
overrides:
  - files:
      - "tests/**/*"
    env:
      jest: true
