interface ITranslate {
  [key: string]: { [key: string]: string };
}

const copies: ITranslate = {
  error: {
    pathnotdefined:
      "Path to report wasn't defined. Please use --path or -p option to define path to the report.",
    reportdoesntexist1: "Report doesn't exist under this:",
    reportdoesntexist2: "path. Make sure that report exists."
  },
  help: {
    default: "default:",
    usage: "Usage:",
    usagecommand:
      "mochawesome-json-to-md -p path/source.json -o path/output.md [args]",
    scriptdescription:
      "Convert your JSON reports generated by Mochawesome to Markdown",
    argumentsheader: "Arguments:",
    helprun: "Run",
    helpcommand: "mochawesome-json-to-md --help",
    helprun1: "for this help",
    moreinfo: "For more information, visit",
    moreinfourl: "https://github.com/403-html/mochawesome-json-to-md"
  },
  args: {
    path: "define path to the json report",
    output: "define path for the output md file",
    template: "define path to the md template",
    help: "show help"
  }
};

export const t = (text: string): string => {
  const [type, key] = text.split(":");
  return copies[type][key];
};
