// option -p, --path; define path to the report
// option -t, --template; default: "../template.md" ;define path to the template
// option -o, --output; define path for the md file
// epilogue; for more information, visit https://github.com/htd-tstepien/mochawesome-json-to-md
// help; show help
// sample usage: $0 -p file/path.json -o file/path.md -t file/path.md
import { white, green } from "colorette";

interface ArgvListI {
  argvs: string[];
  default?: string;
  description: string;
}

const argvList: ArgvListI[] = [
  {
    argvs: ["--path", "-p"],
    description: "define path to the report"
  },
  {
    argvs: ["--output", "-o"],
    description: "define path for the md file"
  },
  {
    argvs: ["--template", "-t"],
    default: "../template.md",
    description: "define path to the template"
  },
  {
    argvs: ["--help", "-h"],
    description: "show help"
  }
];

const normalizeArgvsName = (): void => {
  const allArgvs = argvList.map((argv) => argv.argvs.join(", "));
  const longestArgv: string = allArgvs.reduce((longest, current) =>
    current.length > longest.length ? current : longest
  );
  const diffProcessedArgvs: string[] = allArgvs.map((argv) => {
    const diff = longestArgv.length - argv.length;
    const spaces = " ".repeat(diff);
    return `${argv}${spaces}`;
  });
  argvList.forEach((argument, index) => {
    do {
      argument.argvs.pop();
    } while (argument.argvs.length > 0);
    argument.argvs.push(diffProcessedArgvs[index]);
  });
};

// string:
// white(argvs) default: white(default) green(description)

const argvsString = (): string => {
  normalizeArgvsName();
  return argvList
    .map((argv) =>
      argv.default
        ? `${green(argv.argvs.pop())} default: ${green(argv.default)}; ${white(
            argv.description
          )}`
        : `${green(argv.argvs.pop())}; ${white(argv.description)}`
    )
    .join("\n");
};

export default `${white(
  `Usage: ${green(
    "mochawesome-json-to-md -p path/source.json -o path/output.md [args]"
  )}`
)}

${white("Convert your JSON reports generated by MochAwesome to Markdown")}

${white("Arguments:")}
${argvsString()}

${white(`Run ${green(`mochawesome-json-to-md --help`)} for this help`)}

${white(
  `For more information, visit ${green(
    "https://github.com/403-html/mochawesome-json-to-md"
  )}`
)}`;
