name: ESlint Check
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages, using npm
        run: npm install
      - name: lint run
        run: npm run eslint
