name: PR Semver
on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  update-version:
    if: ${{ github.event.label.name == 'semver' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: reattach HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get current prefix
        id: branch-prefix
        run: echo "::set-output name=prefix::$(echo ${{ github.head_ref }} | cut -d '/' -f 1)"

      - name: Check if branch prefix is valid (major, minor, patch)
        run: |
          echo "Checking branch prefix..."
          echo "branch prefix: ${{ steps.branch-prefix.outputs.prefix }}"
          if [[ ${{ steps.branch-prefix.outputs.prefix }} != "major" && ${{ steps.branch-prefix.outputs.prefix }} != "minor" && ${{ steps.branch-prefix.outputs.prefix }} != "patch" ]]; then
            echo "Branch prefix is not valid, exiting..."
            exit 1
          fi
          echo "Branch prefix is valid"
      - name: Set next version number based on prefix
        run: |
          echo "Getting next version number..."
          if [ "${{ steps.branch-prefix.outputs.prefix }}" == "major" ]; then
            echo "Bumping major version..."
            npm --no-git-tag-version version major
          elif [ "${{ steps.branch-prefix.outputs.prefix }}" == "minor" ]; then
            echo "Bumping minor version..."
            npm --no-git-tag-version version minor
          elif [ "${{ steps.branch-prefix.outputs.prefix }}" == "patch" ]; then
            echo "Bumping patch version..."
            npm --no-git-tag-version version patch
          else
            echo "Error: working branch prefix not found"
            exit 1
          fi
      - name: Setup git
        run: |
          echo "Setting up git..."
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "${{ secrets.MY_USERNAME }}"
      - name: Commit and push changes to working branch
        run: |
          echo "Committing changes..."
          git add .
          git commit -am "chore(release): Bump ${{ steps.branch-prefix.outputs.prefix }} version"
          git push origin HEAD
